### ISSUE TITLE
application health check failed when added envoy side car in pod

### ISSUE THREAD

**Issue by samrui** [aws/aws-app-mesh-controller-for-k8s#147] opened 2020-03-19 04:43 UTC
**Summary**
application health check failed when I added side car in the pod.

**Steps to Reproduce**
I just deployed a java web appliacation.
When namespace doesn't label "appmesh.k8s.aws/sidecarInjectorWebhook=enabled", it works well.
One pod with one container, status is running.

```
[centos@ip-10-103-218-60 k8s]$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
app-a-deployment-69865b99c9-r4qwj      1/1     Running   0          2m5s
```
But when I label namespace with "appmesh.k8s.aws/sidecarInjectorWebhook=enabled" and restart the pod, envoy container can start successfully, but the application container can't start.
The related ELB has no healthy targets.

```
[centos@ip-10-103-218-60 k8s]$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
app-a-deployment-69865b99c9-k96np      1/2     Running   1          2m50s

```

Following is my k8s yaml.
```
apiVersion: v1
kind: Service
metadata:
  namespace: sam-demo
  name: app-a-service
  labels:
    k8s-app: app-a-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    k8s-app: app-a-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sam-demo
  name: app-a-deployment
  labels:
    k8s-app: app-a-deployment

spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: app-a-pod
  template:
    metadata:
      namespace: sam-demo
      name: app-a-pod
      labels:
        k8s-app: app-a-pod
    spec:
      containers:
        - name: app-a-container
          image: xxx.dkr.ecr.us-east-1.amazonaws.com/app-a:1.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 10
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 3

```

**Comment by efe-selcuk** [comment] 2020-04-04 09:17
Hey there. Is that your entire manifest? Or are you also generating a Mesh and VirtualNode? If not, the Envoy container that gets injected wouldn't receive any configuration and couldn't route traffic. That's my initial take on a possible problem

If you haven't seen our examples, you can see how you might configure a sample application: https://github.com/aws/aws-app-mesh-examples/tree/master/walkthroughs/howto-k8s-alb

**Comment by samrui** [comment] 2020-04-07 09:48
@efe-selcuk 
I try it with "howto-k8s-alb". But a new error occurred.
```

[centos@ip-10-103-218-60 _output]$ kubectl apply -f manifest.yaml 
namespace/howto-k8s-alb unchanged
mesh.appmesh.k8s.aws/howto-k8s-alb unchanged
virtualservice.appmesh.k8s.aws/color.howto-k8s-alb.svc.cluster.local unchanged
service/front unchanged
deployment.apps/front unchanged
service/color-green unchanged
deployment.apps/green unchanged
service/color-blue unchanged
deployment.apps/blue unchanged
service/color unchanged
ingress.extensions/color unchanged
Error from server (MethodNotAllowed): error when creating "manifest.yaml": the server does not allow this method on the requested resource (post virtualnodes.appmesh.k8s.aws)
Error from server (MethodNotAllowed): error when creating "manifest.yaml": the server does not allow this method on the requested resource (post virtualnodes.appmesh.k8s.aws)
Error from server (MethodNotAllowed): error when creating "manifest.yaml": the server does not allow this method on the requested resource (post virtualnodes.appmesh.k8s.aws)

```

and pod description has some error
```

Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                                     Message
  ----     ------     ----                  ----                                     -------
  Normal   Scheduled  11m                   default-scheduler                        Successfully assigned howto-k8s-alb/front-5fdb9cb7bb-5rp2p to ip-10-103-219-163.ec2.internal
  Normal   Pulling    11m                   kubelet, ip-10-103-219-163.ec2.internal  Pulling image "111345817488.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-proxy-route-manager:v2"
  Normal   Pulled     10m                   kubelet, ip-10-103-219-163.ec2.internal  Successfully pulled image "111345817488.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-proxy-route-manager:v2"
  Normal   Created    10m                   kubelet, ip-10-103-219-163.ec2.internal  Created container proxyinit
  Normal   Started    10m                   kubelet, ip-10-103-219-163.ec2.internal  Started container proxyinit
  Normal   Pulling    10m                   kubelet, ip-10-103-219-163.ec2.internal  Pulling image "840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.12.2.1-prod"
  Normal   Pulled     10m                   kubelet, ip-10-103-219-163.ec2.internal  Successfully pulled image "840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:v1.12.2.1-prod"
  Normal   Created    10m                   kubelet, ip-10-103-219-163.ec2.internal  Created container envoy
  Normal   Started    10m                   kubelet, ip-10-103-219-163.ec2.internal  Started container envoy
  Warning  Unhealthy  10m                   kubelet, ip-10-103-219-163.ec2.internal  Liveness probe failed: Get http://10.103.219.188:8080/ping: dial tcp 10.103.219.188:8080: connect: connection refused
  Normal   Killing    10m                   kubelet, ip-10-103-219-163.ec2.internal  Container app failed liveness probe, will be restarted
  Normal   Started    9m41s (x2 over 10m)   kubelet, ip-10-103-219-163.ec2.internal  Started container app
  Normal   Created    9m41s (x2 over 10m)   kubelet, ip-10-103-219-163.ec2.internal  Created container app
  Normal   Pulled     9m41s (x2 over 10m)   kubelet, ip-10-103-219-163.ec2.internal  Successfully pulled image "452410912201.dkr.ecr.us-east-1.amazonaws.com/howto-k8s-alb/feapp"
  Normal   Pulling    9m41s (x2 over 10m)   kubelet, ip-10-103-219-163.ec2.internal  Pulling image "452410912201.dkr.ecr.us-east-1.amazonaws.com/howto-k8s-alb/feapp"
  Warning  Unhealthy  6m (x40 over 10m)     kubelet, ip-10-103-219-163.ec2.internal  Readiness probe failed: Get http://10.103.219.188:8080/ping: dial tcp 10.103.219.188:8080: connect: connection refused
  Warning  BackOff    52s (x26 over 7m21s)  kubelet, ip-10-103-219-163.ec2.internal  Back-off restarting failed container

```

**Comment by efe-selcuk** [comment] 2020-04-07 16:58
This is getting into unfamiliar territory for me personally. But I think the logs for the pod are a symptom of the first bit of errors. If the virtual nodes aren't getting created, again your envoy won't have any configuration, so it won't open up the 8080 listener.

[Some cursory searches](https://www.google.com/search?q=k8s+%22the+server+does+not+allow+this+method+on+the+requested+resource%22+post) on the error message yield some sparse issues regarding naming conflicts. I suspect your cluster is in an inconsistent state. Would be interested to see if this repros on a fresh cluster, or at least after blowing away any app mesh resources including the CRDs.

@achevuru @M00nF1sh ideas on troubleshooting?

**Comment by achevuru** [comment] 2020-04-09 00:31
I tried this and it worked as expected. I suspect some config issue on your cluster. Can you share your pod spec (or) check if the virtualNode name is as expected in the pod Spec? If you have multiple meshes in your cluster, then please make sure correct meshName was used to construct the VirtualNode name. Should be something like below for the example under howto-k8s-alb...If not, packets will not flow through via Envoy .... App Mesh Inject is using an env variable for mesh Name and it might result in using an incorrect mesh name with multiple meshes..

    - name: APPMESH_VIRTUAL_NODE_NAME
      value: mesh/howto-k8s-alb/virtualNode/blue-howto-k8s-alb

I see that VirtualNode creation itself failed for you based on the above logs...Can you check if the VirtualNode CRD is in place?

**Comment by astrived** [comment] 2020-04-15 20:03
@samrui do you have any update ? based on @achevuru's reproduction does show that this may be a config issue.

**Comment by astrived** [comment] 2020-04-22 20:40
@samrui given that we were not able to reproduce the issue and have not heard from you, we are closing the issue, please reopen if the config change suggested does not address your issue.

**Closed by astrived** 2020-04-22 20:40 UTC
Labels: Priority: High, bug
