### ISSUE TITLE
Update appmesh.k8s.aws spec to support preview channel functionalities

### ISSUE THREAD

**Issue by cdmadrigal** [aws/aws-app-mesh-controller-for-k8s#120] opened 2020-01-15 23:13 UTC
At the moment, the appmesh api [spec](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/deploy/all.yaml) doesn't support TLS encryption. 

This is a preview channel functionality that is supported by ECS and should be extended to K8s/EKS for testing purposes before general release.

**Comment by lavignes** [comment] 2020-01-15 23:30
Hey @cdmadrigal thanks for showing interest in this new feature!

I'm going to resolve this as a duplicate of #75 though. So feel free to comment there, too. :)

**Closed by lavignes** 2020-01-15 23:30 UTC
