### ISSUE TITLE
Don't delete Mesh resources that aren't owned by the cluster

### ISSUE THREAD

**Issue by otterley** [aws/aws-app-mesh-controller-for-k8s#342] opened 2020-08-12 23:50 UTC
Currently the App Mesh Controller will attempt to delete an App Mesh mesh when its corresponding Kubernetes resource is deleted. This is a problem for meshes that span K8S cluster boundaries, since the Mesh may need to survive destruction of the cluster.

The controller should attempt to delete a Mesh only if it was created by the cluster itself.

**Comment by fawadkhaliq** [comment] 2020-09-13 19:38
This issue a duplicate of https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/101. We're planning to fix https://github.com/aws/aws-app-mesh-controller-for-k8s/issues/101 in the next [release](https://github.com/aws/aws-app-mesh-controller-for-k8s/milestone/7)

**Closed by fawadkhaliq** 2020-09-13 19:38 UTC
