### ISSUE TITLE
TooManyRequestsException being triggered

### ISSUE THREAD

**Issue by lavignes** [aws/aws-app-mesh-controller-for-k8s#96] opened 2019-11-06 00:46 UTC
I've been seeing `TooManyRequestsException`s being returned from App Mesh  frequently in the controller logs.

What sort of rate-limiting or back-off does the controller do? Is it configurable?

**Comment by stefanprodan** [comment] 2019-11-06 07:30
There is no rate-limiting in place as far as I'm aware, the controller reconciles all objects found in the cluster every [30s](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/cmd/app-mesh-controller/root.go#L110) and does an API call to App Mesh for each object from [5 threads](https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/master/pkg/controller/controller.go#L31). I think the controller should detect changes in the Kubernetes custom resources and call the App Mesh API only for those objects. This can be achieved using the `cmp` package, [here](https://github.com/weaveworks/flagger/blob/master/pkg/controller/controller.go#L127) is an example. Right now if you have 100 virtual nodes in a cluster, the controller will do 100 POST requests to App Mesh even if none of the virtual nodes have changed since the last sync. 

PS. I'm planning to instrument the controller and expose Prometheus metrics for the API requests. We will be able to monitor the req/sec rate, error rate and latency between the controller and App Mesh API to better undestand where the problem is.

**Comment by stefanprodan** [comment] 2019-11-06 09:20
After instrumenting the App Mesh API calls this is what's happening 500 req/min with just a handful of objects (5 nodes and 2 virtual service) 😱 

<img width="1462" alt="Screenshot 2019-11-06 at 11 18 10" src="https://user-images.githubusercontent.com/3797675/68285141-66975480-0087-11ea-8240-6b66ce7ab463.png">

**Comment by nckturner** [comment] 2019-11-06 18:15
@lavignes how many App Mesh objects do you have in your cluster?

**Comment by nckturner** [comment] 2019-11-17 06:30
>  I think the controller should detect changes in the Kubernetes custom resources and call the App Mesh API only for those objects. 

I think we also want to overwrite objects that are modified in the App Mesh API as soon as possible so we need to temporarily query the API regardless of whether the custom resource changed. (Doesn't have to be every time, of course).

**Comment by dastbe** [comment] 2019-11-17 17:47
Rate limiting in the controller gets rid of the exceptions, but I don’t think that gets to what the customer experience should be here and what scale we should be designing for. If I get 10 tps to App Mesh, then I can just barely describe 300 resources every 30s (not even considering mutation for now).

So let’s think about, for a 30s period

1. How many resources can be actively managed?
1. How many resources can be actively mutated?

IMO, my initial guess for our desired scale here is 10,000s active management and 10s-100s actively mutated. I have some thoughts about both numbers, but I’ll focus on active management. 

On the App Mesh side, we can raise throttles to help mitigate the current scaling limit. But long-term, we need a simple way for the controller to reconcile very efficiently. Given we don’t have a bath describe API, can we provide sufficient information in our list APIs? For example, if we provided:

* resource name
* resource uid
* resource version

In a list response, that would be enough information to reconcile configuration drift whether it’s missing resources or resources that were modified/created by someone not the controller. This would also be relatively straightforward for us to expose. Would this be something the controller could leverage by persisting this state?

With list responses of 100, that same 10 tps gets us to 30k resources every 30s, and increasing the max max results from a list to 1000 gets us 300k in 30s, or 30k in 3 seconds. Similar benefits come from increasing throttle limits for reads.

**Comment by efe-selcuk** [comment] 2020-03-06 00:03
I wonder if #133 and subsequently #134 will help here

**Comment by bcelenza** [comment] 2020-03-06 01:57
I believe they will help on mutations, but there is still a decent steady state load of describes on larger meshes that will see rate exceeded exceptions.

**Comment by achevuru** [comment] 2020-05-08 06:34
PR #163 should've fixed it

**Comment by achevuru** [comment] 2020-05-14 17:43
Fix Available in v0.5.0. Upcoming GA release will also have a fix for this.

**Closed by achevuru** 2020-05-14 17:43 UTC
Labels: GA_1.0, Priority: High, Roadmap: Researching
