### ISSUE TITLE
[Bug] v1beta2: Controller fails to renew lease for leader election

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-controller-for-k8s#260] opened 2020-06-08 18:53 UTC
This is potentially related to #259 since my controller is in an error loop. However, I'm noticing that the v1beta2 branch controller crashes every so often with the following error:

```
E0608 18:51:04.249990       1 leaderelection.go:320] error retrieving resource lock appmesh-system/f4abe831.k8s.aws: Get "https://10.100.0.1:443/api/v1/namespaces/appmesh-system/configmaps/f4abe831.k8s.aws": context deadline exceeded
I0608 18:51:04.250036       1 leaderelection.go:277] failed to renew lease appmesh-system/f4abe831.k8s.aws: timed out waiting for the condition
{"level":"error","ts":1591642264.2500608,"logger":"setup","msg":"problem running manager","error":"leader election lost","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128\nmain.main\n\t/workspace/main.go:194\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"}
```

After this it restarts and resumes reconciliation, crashing again after some time.

Controller version:
```
{"level":"info","ts":1591642276.2225752,"logger":"setup","msg":"version","GitVersion":"5f6990f-dirty","GitCommit":"5f6990f981ec89fd4e7ffd6c1fccd3a4f2cbeee1","BuildDate":"2020-06-05T21:22:43+0000"}
```

Can confirm that lease is acquired when controller first starts:
```
I0608 18:51:24.235019       1 leaderelection.go:242] attempting to acquire leader lease  appmesh-system/f4abe831.k8s.aws...
I0608 18:51:41.513125       1 leaderelection.go:252] successfully acquired lease appmesh-system/f4abe831.k8s.aws
```

**Comment by M00nF1sh** [comment] 2020-06-08 19:12
seems your control plane is having issues. did you have a mass number of objects in your cluster?

**Comment by bcelenza** [comment] 2020-06-08 19:23
Less than 10.

**Comment by bcelenza** [comment] 2020-06-08 19:26
Once I resolved the issue from #259 the controller appears to be stable. Perhaps related to the error case?

**Comment by fawadkhaliq** [comment] 2020-06-11 01:39
This is definitely a transient issue and does not seem to be related to the error seen in #259 . This is likely due to etcd or api server going through some state that caused this or transient network issue. The issue is not reproducible even when controller is complaining about missing dependency or throwing other unrelated errors. Worth investigating to find the root cause if seen again and other controllers will go through the same

In either case, the controller should automatically recover from transient errors

**Comment by M00nF1sh** [comment] 2020-06-18 18:00
close this as it's should due to cp availbility and not reproducible. will reopen if we got a reproduce.

**Closed by M00nF1sh** 2020-06-18 18:00 UTC
Labels: bug
