### ISSUE TITLE
add annotation "appmesh.k8s.aws/mesh: ${MESH_NAME}" in file "...examples/color.yaml.template"

### ISSUE THREAD

**Issue by XiaoYangZhu** [aws/aws-app-mesh-controller-for-k8s#106] opened 2019-11-22 11:06 UTC
It will be a good enhancement to add annotation as below in the file "examples/color.yaml.template" to provide more flexibility for the color app deployment in order to provide more flexibility control on the mesh where the app will be provisioned under.

###########
...
template:
    metadata:
      annotations:
        appmesh.k8s.aws/mesh: ${MESH_NAME}
...
###########

**Comment by shubharao** [comment] 2020-02-05 21:52
Duplicate of #32

**Closed by shubharao** 2020-02-05 21:52 UTC
Labels: enhancement, good first issue
