### ISSUE TITLE
[Bug] Egress-only virtual node on Fargate pod stuck @ ContainerCreating status

### ISSUE THREAD

**Issue by bcelenza** [aws/aws-app-mesh-controller-for-k8s#263] opened 2020-06-10 00:14 UTC
Using the following Virtual Node configuration:

```
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: cuckoo-v1
  namespace: aviary
spec:
  podSelector:
    matchLabels:
      app: cuckoo
      version: v1
  backends:
    - virtualService:
        virtualServiceRef:
          name: mockingbird
  logging:
    accessLog:
      file:
        path: /dev/stdout
```

When pods launch, they become stuck at the `ContainerCreating` state. Describing the pods provides a hint at the issue:

```
kubectl -n aviary describe pod cuckoo-867b48966-ncfrh
Name:                 cuckoo-867b48966-ncfrh
Namespace:            aviary
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 fargate-ip-192-168-68-171.ec2.internal/192.168.68.171
Start Time:           Tue, 09 Jun 2020 17:01:46 -0700
Labels:               app=cuckoo
                      eks.amazonaws.com/fargate-profile=fp-aviary
                      pod-template-hash=867b48966
                      version=v1
Annotations:          appmesh.k8s.aws/egressIgnoredIPs: 169.254.169.254
                      appmesh.k8s.aws/egressIgnoredPorts: 22
                      appmesh.k8s.aws/ignoredUID: 1337
                      appmesh.k8s.aws/ports: 0
                      appmesh.k8s.aws/proxyEgressPort: 15001
                      appmesh.k8s.aws/proxyIngressPort: 15000
                      appmesh.k8s.aws/sidecarInjectorWebhook: enabled
                      kubernetes.io/psp: eks.privileged
Status:               Pending
IP:
IPs:                  <none>
Controlled By:        ReplicaSet/cuckoo-867b48966
Containers:
  usurper:
    Container ID:
    Image:          bcelenza/usurper
    Image ID:
    Port:           22/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      AWS_ROLE_ARN:                 arn:aws:iam::027496699299:role/eksctl-aviary-addon-iamserviceaccount-aviary-Role1-1EYT7QXFQ6RA6
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from aviary-pods-token-qq5bt (ro)
  envoy:
    Container ID:
    Image:          840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.12.3.0-prod
    Image ID:
    Port:           9901/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     10m
      memory:  32Mi
    Environment:
      APPMESH_VIRTUAL_NODE_NAME:    mesh/aviary/virtualNode/cuckoo-v1_aviary
      APPMESH_PREVIEW:              0
      ENVOY_LOG_LEVEL:              info
      AWS_REGION:                   us-east-1
      AWS_ROLE_ARN:                 arn:aws:iam::027496699299:role/eksctl-aviary-addon-iamserviceaccount-aviary-Role1-1EYT7QXFQ6RA6
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
  aviary-pods-token-qq5bt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  aviary-pods-token-qq5bt
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age        From                                             Message
  ----     ------                  ----       ----                                             -------
  Normal   Scheduled               <unknown>  fargate-scheduler                                Successfully assigned aviary/cuckoo-867b48966-ncfrh to fargate-ip-192-168-68-171.ec2.internal
  Warning  FailedCreatePodSandBox  31s        kubelet, fargate-ip-192-168-68-171.ec2.internal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4ebf8738ff14da1a45c6cb1fd6ecfb7864625e1828cfc178714d2a340a0fb0bc": invalid port [0] specified
  Warning  FailedCreatePodSandBox  16s        kubelet, fargate-ip-192-168-68-171.ec2.internal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "6da910e5e9a91e0e14b4e9e743e9ff8f51b05dcb91e700855e520e0a63e33089": invalid port [0] specified
  Warning  FailedCreatePodSandBox  3s         kubelet, fargate-ip-192-168-68-171.ec2.internal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "8a6fe23b2ad9cd7b79decf5b3c6eb451aea61b26491164d6e01171615c31d305": invalid port [0] specified
```

I believe this may be related to the temporary change for aws/aws-app-mesh-inject#47 which injects "0" as the port if no Virtual Node listener is provided. Setting a listener on the virtual node resolves the issue.

**Comment by M00nF1sh** [comment] 2020-06-11 00:11
the "0" trick only works for normal pods(which use initContainer and iptables), for fargate pod u are using, it's using cni to intercept traffic, and the validation is there.
we need to update cni to support it.

**Comment by M00nF1sh** [comment] 2020-06-11 00:15
the error message come from https://github.com/aws/amazon-vpc-cni-plugins/blob/ee068761f66eff4603e0291986465aa1fc1d9f9b/plugins/aws-appmesh/config/netconfig.go#L201.

**Comment by bcelenza** [comment] 2020-06-11 16:10
Looks like we have aws/amazon-vpc-cni-plugins#12 open to resolve this for the CNI. Will rename this issue accordingly.

**Comment by fawadkhaliq** [comment] 2020-06-11 17:23
_To summarize_

The issue is there when using egress only virtual node/pod on EKS Fargate. The fix is in CNI plugin mentioned above

Until the issue is fixed aws/amazon-vpc-cni-plugins#12, the only workaround is to add a dummy listener

**Comment by bcelenza** [comment] 2020-06-13 17:52
Updated PR link for CNI plugin: https://github.com/aws/amazon-vpc-cni-plugins/pull/37

**Comment by fawadkhaliq** [comment] 2020-08-03 22:12
CNI code is merged - check what else is needed for this

**Comment by M00nF1sh** [comment] 2020-08-03 22:20
did we treat '0' as empty appPorts? if not, we need to change our injector to not inject the appPorts annotation instead.
Also, we need to include this version of cni into our fargate task image.

**Comment by fawadkhaliq** [comment] 2020-08-03 22:35
Yes, the port part, release and check on other things that need to be addressed before we can close it

**Comment by fawadkhaliq** [comment] 2020-08-11 20:49
This issue is being punted to the next release. There's pending work to publish CNI fix (https://github.com/aws/amazon-vpc-cni-plugins/pull/37) in the Fargate task image and corresponding changes here + testing

**Comment by fawadkhaliq** [comment] 2020-11-02 01:37
CNI plugin changes: https://github.com/aws/amazon-vpc-cni-plugins/pull/37
Controller changes: https://github.com/aws/aws-app-mesh-controller-for-k8s/pull/373

The CNI plugin changes will published to the upcoming default of Fargate task image

**Closed by fawadkhaliq** 2020-11-02 01:37 UTC
Labels: bug
